#!/bin/bash
rm -f managebox.tar.gz
curl http://managebox.ir/download/latest.tar.gz -o managebox.tar.gz -s
rm -rf /usr/local/managebox
mkdir /usr/local/managebox
tar -xzf managebox.tar.gz -C /usr/local/managebox
rm -f managebox.tar.gz

chmod 700 /usr/local/managebox
chmod 700 /usr/local/managebox/scripts
chmod 700 /usr/local/managebox/data
chmod 700 /usr/local/managebox/data/main
chmod 600 /usr/local/managebox/data/main/*
chmod 700 /usr/local/managebox/scripts/*
/usr/local/managebox/scripts/install-requirments
/usr/local/managebox/scripts/mysql-secure
